### PR TITLE
add simple sts native support

### PR DESCRIPTION
**Pull request by nicolas-vivot**
This PR is to add simple native support for STS in Quarkus.

The intention here is to provide a substitution for the static code using reflection and avoid to have to add reflection configuration on applications.
Please refers to the following issues for more informations.

https://github.com/quarkusio/quarkus/issues/6488

https://github.com/quarkusio/quarkus/issues/14061#issuecomment-754615881

I did not add the documentation and added empty integration tests. Please complete it whenever you need with real usage tests.

### CODE REVIEW

**Review by gsmet — CHANGES_REQUESTED** [review]
Thanks for this work but we really need someone to add some simple tests and documentation. It doesn't need to be as complete as the rest but we at least need something.

**Review by oscerd — APPROVED** [review]
I think this is a good start nevertheless, thanks a lot @nicolas-vivot

**Comment by elrob** [comment]
FYI: I think this is related: https://github.com/aws/aws-sdk-java-v2/issues/2985

**Comment by brianwyka** [comment]
And updates on completing this one?

**Comment by nicolas-vivot** [comment]
The compatibility with native image has been fixed on aws side starting from 2.17.201

So if you are using Quarkus 2.8+ you should depends on a higher version of aws library, therefore do not need any substitution anymore for the auth part.
If you are still on Quarkus 2.7.x like me, you still need to substitute it.

Since the original purpose of the PR was to have that substitution and this does not make sense anymore now it's been fixed on the source lib, let's close this PR.

**Comment by nicolas-vivot** [comment]
Sorry, re-open, my mistake.

**Comment by elrob** [comment]
> The compatibility with native image has been fixed on aws side starting from 2.17.201

> Sorry, re-open, my mistake.

Ah, thank you. I just started looking through aws changelog for the STS fix and couldn't find it.

**Comment by scrocquesel** [comment]
superseded by https://github.com/quarkiverse/quarkus-amazon-services/pull/591

**Pull request closed without merging**
