### PR TITLE
Provide support for aws crt async client

### LINKED ISSUE #645: Support AwsCrtAsyncHttpClient
https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/http-configuration-crt.html

### PR DESCRIPTION
**Pull request by scrocquesel**
Initial support

Closes #645

### CODE REVIEW

**Comment by scrocquesel** [comment]
Need some native compilation check and will need later to split netty specific configuration to a dedicated config class but will be a breaking change

**Comment by scrocquesel** [comment]
> Need some native compilation check and will need later to split netty specific configuration to a dedicated config class but will be a breaking change

https://github.com/aws/aws-sdk-java-v2/issues/2948

**Comment by scrocquesel** [comment]
@gsmet Do you know someone who can help with JNI stuff? I'm having trouble getting it to work with Quarkus, even though someone in the AWS issue above provided a repo with a working native solution. I keep getting a `java.lang.UnsatisfiedLinkError`. I believe it might be related to this issue https://github.com/quarkusio/quarkus/issues/12469 but I barely know anything about JNI.

**Comment by scrocquesel** [comment]
@hamburml @Temdegon Still very experimental, but it should be working with dynamodb.

Replace 
```pom.xml
<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>netty-nio-client</artifactId>
    <optional>true</optional>
</dependency>
```
with 
```pom.xml
 <dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>aws-crt-client</artifactId>
    <optional>true</optional>
</dependency>
```

Or you can even add both and set the client type for a specific service `quarkus.kms.async-client.type=aws-crt` as in integration-tests.

Require upgrading to Quarkus 3.0. If you could have a try and let me know. If you are doing some `quarkus-amazon-lambda` deployment, would like to know if it works too as it certainly will be the main use case why to choose this implementation.

**Comment by Temdegon** [comment]
@scrocquesel I wouldn't be able to try this at real project in nearest future. We are using quarkus for aws-lambda but not using nio at all currently, and I have zero experience with nio at all. I was interested in this ticket bcs there are many recommendations to use this client, saying it reduces coldstart, but there were no out-of-the-box support of this client. 
Right now we've mostly solved lambda coldstart with snap start.
But anyway, thanks for your effort. I'll definitely give it a try if I have suitable task where nio makes sense.

**Comment by scrocquesel** [comment]
I did some tests with lambda and it did works with dynamodb.

**Comment by hamburml** [comment]
Sorry, I havent had enough time. Hopefully next week :)

**Pull request merged**
