### PR TITLE
Issue 794: added command for localstack dev service configuration

### PR DESCRIPTION
**Pull request by pfaul**
I added the option to pass a command to the docker container during the startup phase.

### CODE REVIEW

**Comment by scrocquesel** [comment]
What would be the command to specify the devservice port ? Would you mind elaborate more on your use case ?
The general idea is to offer strongly typed config for a better developer discovery experience.

Otherwise, I think a list of string may be a better option

**Comment by pfaul** [comment]
Sure thing.
My use case is setting up an event based communication between two quarkus services using the sns and sqs devservices. 
With the config flags "shared" I could not manage to get a successful local setup. The "shared" flag of the devservices forces two different localstack containers to be run. In this case, the SQS queue is never able to receive published events from the other localstack container (sns).
This is why I ended up using the "endpoint-override" configuration to locally test the communication inside one single localstack container. Now since, the exposed port of the localstack container is randomly generated, I can not achieve a stable test setup. This is why I put some effort into researching how to configure exposed ports in a docker container and found this article:
https://www.mend.io/free-developer-tools/blog/docker-expose-port/

From my point of view, the testcontainers library is able to translate a single String parameter of multiple arguments seemlessly, see here for reference: https://java.testcontainers.org/features/commands/

This is why I proposed this PR with an Optional<String> instead of a List, which might force users to provide a parameter instead of none.
The command to expose the port should be "-p XXXX:4566", where XXXX is the port you wish to expose.

**Comment by scrocquesel** [comment]
> Sure thing. My use case is setting up an event based communication between two quarkus services using the sns and sqs devservices. With the config flags "shared" I could not manage to get a successful local setup. The "shared" flag of the devservices forces two different localstack containers to be run. In this case, the SQS queue is never able to receive published events from the other localstack container (sns). This is why I ended up using the "endpoint-override" configuration to locally test the communication inside one single localstack container. Now since, the exposed port of the localstack container is randomly generated, I can not achieve a stable test setup. This is why I put some effort into researching how to configure exposed ports in a docker container and found this article: https://www.mend.io/free-developer-tools/blog/docker-expose-port/
> 
> From my point of view, the testcontainers library is able to translate a single String parameter of multiple arguments seemlessly, see here for reference: https://java.testcontainers.org/features/commands/
> 
> This is why I proposed this PR with an Optional instead of a List, which might force users to provide a parameter instead of none. The command to expose the port should be "-p XXXX:4566", where XXXX is the port you wish to expose.

Could you open an issue ? I need to have a deeper look into it but the scenario you describe should already be handled https://docs.quarkiverse.io/quarkus-amazon-services/dev/dev-services.html#_shared_services

The issue with `withCommand` is that it will only override the command the image will execute. It is not intended as arguments for docker run. So you may be able to make localstack listen to a port but it will not be exposed by docker. You would need to combine that with `withExposedPorts`.

**Comment by pfaul** [comment]
Alright. Yes I will open an issue. Now that we discussed about it, my PR feels more like a workaround to the real problem.

I've read the documentation about the "shared" flag, but please read my latest post again. The containers can't talk to each other, which is why I was looking for a different solution.

**Pull request closed without merging**
