### PR TITLE
Use Method#invoke instead of MethodHandle as workaround of graal native-image bug

### LINKED ISSUE #416: @DynamoDBVersionAttribute with dynamodb-enhanced not working in native mode
First of all, thanks for your work on Quarkus/Quarkiverse. We really enjoy working with Quarkus. :)

We are using Quarkus version 2.14.3.Final and quarkus-amazon-services version 1.3.1

To access DynamoDb we use the `quarkus-amazon-dynamodb-enhanced` extension.
Now we want to introduce opmtistic locking for an entity. https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.OptimisticLocking.html

We added a field with the annotation `@DynamoDBVersionAttribute` which is provided by the aws SDK for this purpose.

Non-native it works as expected (version is set to 1 on insertion, then incremented with each update). Native a `ConditionalCheckFailedException` is thrown while inserting a new entity.

Based on https://github.com/quarkusio/quarkus-quickstarts/tree/main/amazon-dynamodb-quickstart and https://quarkiverse.github.io/quarkiverse-docs/quarkus-amazon-services/dev/amazon-dynamodb.html#_dynamodb_enhanced_client I prepared a sample project to reproduce the issue.

You can find the sample project at https://github.com/dagrammy/DynamoDbVersionAttribute-test.

`./mvnw install` -> BUILD SUCCESS
`./mvnw install -Dnative` -> BUILD FAILURE

Complete log: https://github.com/dagrammy/DynamoDbVersionAttribute-test/blob/main/README.md
```
 HTTP Request to /fruits failed, error id: 641e581d-abc1-4585-8ddb-bec115b262b3-1: software.amazon.awssdk.services.dynamodb.model.ConditionalCheckFailedException: The conditional request failed (Service: DynamoDb, Status Code: 400, Request ID: ODARM82TCOGF31YLKRI9QIU57OGW2SNPZ1DJTCVW9PFX3NY3D74C)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:125)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:82)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:60)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:41)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36)
```

Is there a way to use the opmtistic locking feature in native builds?

Thanks in advance!

### PR DESCRIPTION
**Pull request by dagrammy**
This PR is a workaround/fix for the problem with optimistic locking in dynamodb-enhanced-client using a native image.

The problem could be traced down to a getter called by `MethodHandle#invoke`.

s. https://github.com/quarkiverse/quarkus-amazon-services/issues/416 for more detailed information.

Fixes #416

### CODE REVIEW

**Comment by gsmet** [comment]
I reorganized the commits a bit. Authorship is maintained even if GitHub doesn't show it (you probably have a mismatch between the email you use for the commits and the emails declared in your GitHub account).

Will merge as soon as CI is green.

**Comment by gsmet** [comment]
Thanks for this work, very much appreciated. I will cut a release once the other pull requests are merged!

**Comment by dagrammy** [comment]
> I reorganized the commits a bit. Authorship is maintained even if GitHub doesn't show it (you probably have a mismatch between the email you use for the commits and the emails declared in your GitHub account).

Thanks for reorganizing the commits. And yes, you are right. I do have a mismatch between the email I used for the commits and the email in my account. 🤦‍♂️ 

> Thanks for this work, very much appreciated. I will cut a release once the other pull requests are merged!
>

You are welcome. 😊 And also many thanks to all for your great work!

**Comment by gsmet** [comment]
@allcontributors add @dagrammy for code

**Pull request merged**
