### PR TITLE
AWS Inspector2 support

### PR DESCRIPTION
**Pull request by javaduke**
As it turns out, AWS SDK has two APIs, `Inspector` and `Inspector2`. This PR adds support for the `Inspector2` API.

### CODE REVIEW

**Comment by javaduke** [comment]
Addresses issue #1245.

**Comment by scrocquesel** [comment]
Are both extensions really necessary ?

**Comment by javaduke** [comment]
To be honest, I don't know. It seems like they are not exactly the same, in my particular case Inspector2 does provide a lot of info that Inspector1 does not, but I cannot be 100% sure if this is always the case. Perhaps it's a good idea to have both.

**Comment by scrocquesel** [comment]
> To be honest, I don't know. It seems like they are not exactly the same, in my particular case Inspector2 does provide a lot of info that Inspector1 does not, but I cannot be 100% sure if this is always the case. Perhaps it's a good idea to have both.

Can you update the list in the root README ? missed it for inspector

**Comment by javaduke** [comment]
Done :)

**Pull request merged**
